SELECT * FROM dbo.COWID_DEATHS ORDER BY Location, date
SELECT * FROM dbo.COWID_VACCINATIONS ORDER BY Location, date

DROP TABLE PORTFOLIO_PROJECT.dbo.COWID_DEATHS
DROP TABLE PORTFOLIO_PROJECT.dbo.COWID_VACCINATIONS

SELECT LOCATION,DATE,TOTAL_CASES,NEW_CASES,TOTAL_DEATHS,POPULATION FROM dbo.COWID_DEATHS ORDER BY Location, date

SELECT LOCATION,DATE,TOTAL_CASES,TOTAL_DEATHS,((TOTAL_DEATHS/TOTAL_CASES) *100) AS PERCENTAGE_OF_DEATH 
FROM dbo.COWID_DEATHS WHERE LOCATION='India' ORDER BY PERCENTAGE_OF_DEATH 

SELECT TOTAL_CASES FROM PORTFOLIO_PROJECT.dbo.COWID_DEATHS
ALTER TABLE PORTFOLIO_PROJECT.dbo.COWID_DEATHS
ALTER COLUMN TOTAL_DEATHS FLOAT

SELECT LOCATION,POPULATION,SUM(TOTAL_CASES),SUM(TOTAL_DEATHS) FROM PORTFOLIO_PROJECT.dbo.COWID_DEATHS
GROUP BY LOCATION,POPULATION

SELECT LOCATION,POPULATION,MAX(TOTAL_CASES) AS Highes_TOTALCASES_COUNT,
MAX((TOTAL_CASES/POPULATION) * 100) AS TOTAL_PERCENT_INFECTED
FROM PORTFOLIO_PROJECT.dbo.COWID_DEATHS GROUP BY LOCATION,POPULATION
ORDER BY TOTAL_PERCENT_INFECTED DESC


SELECT LOCATION,MAX(TOTAL_DEATHS) AS Highes_DEATH_COUNT
FROM PORTFOLIO_PROJECT.dbo.COWID_DEATHS WHERE CONTINENT IS NULL
GROUP BY LOCATION
ORDER BY Highes_DEATH_COUNT DESC

SELECT CONTINENT,SUM(NEW_CASES), SUM(NEW_DEATHS),(SUM(NEW_DEATHS)/SUM(NEW_CASES))AS DEATH_PERCENTAGE
FROM dbo.COWID_DEATHS
WHERE CONTINENT IS NOT NULL AND CONTINENT='ASIA'
GROUP BY CONTINENT ORDER BY 2,3


SELECT SUM(NEW_CASES), SUM(NEW_DEATHS),(SUM(NEW_DEATHS)/SUM(NEW_CASES))AS DEATH_PERCENTAGE
FROM dbo.COWID_DEATHS
WHERE CONTINENT IS NOT NULL


SELECT SUM(NEW_CASES), SUM(NEW_DEATHS),(SUM(NEW_DEATHS)/SUM(NEW_CASES))AS DEATH_PERCENTAGE
FROM dbo.COWID_DEATHS

SELECT Dth.CONTINENT , Dth.DATE, Dth.LOCATION, Dth.LOCATION, Vcine.New_vaccinations, 
SUM(New_Vaccinations) OVER (PARTITION BY Dth.LOCATION, Dth.DATE)
FROM dbo.COWID_DEATHS Dth
INNER JOIN dbo.COWID_VACCINATIONS Vcine
ON Dth.LOCATION = Vcine.LOCATION AND Dth.DATE = Vcine.DATE
WHERE CONTINENT IS NOT NULL


SELECT 
    Dth.CONTINENT,
    Dth.DATE,
    Dth.LOCATION,
    Vcine.New_vaccinations,
    SUM(CAST(Vcine.New_vaccinations AS BIGINT)) OVER (PARTITION BY Dth.LOCATION ORDER BY Dth.LOCATION,Dth.DATE) AS TOTALCASES_DAYBYDAY
FROM 
    dbo.COWID_DEATHS Dth
INNER JOIN 
    dbo.COWID_VACCINATIONS Vcine ON Dth.LOCATION = Vcine.LOCATION AND Dth.DATE = Vcine.DATE
WHERE 
    Dth.CONTINENT IS NOT NULL 
ORDER BY Dth.LOCATION,Dth.DATE




WITH CTE AS (
    SELECT 
        Dth.CONTINENT,
        Dth.DATE,
        Dth.LOCATION,
        Dth.POPULATION,  -- Assuming the population column is in dbo.COWID_DEATHS
        Vcine.New_vaccinations,
        SUM(CAST(Vcine.New_vaccinations AS BIGINT)) OVER (PARTITION BY Dth.LOCATION ORDER BY Dth.LOCATION, Dth.DATE) AS TOTALCASES_DAYBYDAY
    FROM 
        dbo.COWID_DEATHS Dth
    INNER JOIN 
        dbo.COWID_VACCINATIONS Vcine ON Dth.LOCATION = Vcine.LOCATION AND Dth.DATE = Vcine.DATE
    WHERE 
        Dth.CONTINENT IS NOT NULL
)
SELECT 
    CTE.CONTINENT,
    CTE.LOCATION,
    MAX(CTE.TOTALCASES_DAYBYDAY) AS MAX_TOTALCASES_DAYBYDAY,
    CTE.POPULATION  -- Include the population column in the final SELECT
FROM 
    CTE
GROUP BY 
    CTE.CONTINENT, CTE.LOCATION, CTE.POPULATION;



WITH CTE AS (
    SELECT 
        Dth.CONTINENT,
        Dth.DATE,
        Dth.LOCATION,
        Dth.POPULATION,
        Vcine.New_vaccinations,
        SUM(CAST(Vcine.New_vaccinations AS BIGINT)) OVER (PARTITION BY Dth.LOCATION ORDER BY Dth.LOCATION, Dth.DATE) AS TOTALCASES_DAYBYDAY
    FROM 
        dbo.COWID_DEATHS Dth
    INNER JOIN 
        dbo.COWID_VACCINATIONS Vcine ON Dth.LOCATION = Vcine.LOCATION AND Dth.DATE = Vcine.DATE
    WHERE 
        Dth.CONTINENT IS NOT NULL
)
SELECT 
    CTE.CONTINENT,
    CTE.LOCATION,
    MAX(CTE.TOTALCASES_DAYBYDAY) AS MAX_TOTALCASES_DAYBYDAY,
    CTE.POPULATION,
    (MAX(CTE.TOTALCASES_DAYBYDAY) * 100.0) / NULLIF(CTE.POPULATION, 0) AS PERCENTAGE
FROM 
    CTE
GROUP BY 
    CTE.CONTINENT, CTE.LOCATION, CTE.POPULATION;


